### ISSUE TITLE
Issues with peer dependency list

### ISSUE THREAD

**Issue by remy90** [payloadcms/eslint-config#2]
When upgrading to 1.x, I run `yarn info @payloadcms/eslint-config peerDependencies` to find no dependencies listed, however running yarn lint results in a list of uninstalled dependencies,
including: eslint-plugin-jest, eslint-plugin-jsx-a11y, eslint-plugin-regexp...

**Comment by DanRibbens** [comment]
This repo should be deprecated from moving to our monorepo back from the 2.0 launch.

https://github.com/payloadcms/payload/tree/main/packages/eslint-config-payload
You can find the full migration to Payload 2.x in the release notes: https://github.com/payloadcms/payload/releases/tag/v2.0.0

Please open an issue on the main repo if you still have any trouble. I'm going to close this but feel free to @ me if you still have questions here.
